### ISSUE TITLE
Mismatch between selected article in plotly graphic and "selected text" with recalculation

### ISSUE THREAD

**Issue by Joemillard** [mjwestgate/revtools#16]
Love this package, I really want to make it a more permanent part of my workflow. A couple of largely ui based comments I'll post as separate issues, which would definitely make me want to use it more. 

I've been experimenting with the article exclusion implementation in Shiny, and noticed that after recalculating the model, selecting a given article seems not to correspond to the "selected text" article. For example, I hover over an article and it reveals "Effects of low temperature..." and then I select it and "selected text" indicates it as "Population density and size influence". When I then click "Exclude" the article it excludes is that indicated by "selected text" and not the article hovered over. The revtools biorxiv paper says that the intention is that users recalculate after excluding articles, so I'm assuming articles in plotly space and the text output should correspond after rerunning.

**Comment by mjwestgate** [comment]
Thanks Joe, I'm really glad you like revtools! Sorry to hear you're having trouble - the version on GitHub has been completely rebuilt lately, so there are still a few bugs (as you've seen!). In the short term you can use the older CRAN version, which shouldn't have these problems. Obviously this bug is an important one, though, so I'll aim to fix it in the next week or so.

**Comment by Joemillard** [comment]
No problem, definitely a package I'll be recommending to others! Ahh I see that makes sense, I'll take a look at the CRAN version in the meantime in that case. Thanks again
